# Generated by Django 4.2.5 on 2023-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('dueDate', models.DateField()),
            ],
        ),
    ]
