# Generated by Django 4.2.5 on 2023-12-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='refrence',
            new_name='reference',
        ),
    ]
